
services:
  pg-catalog:
    image: postgres:17.3
    container_name: pg_catalog
    networks:
      iceberg-net:
    environment:
      - POSTGRES_USER=kxuiceberg
      - POSTGRES_PASSWORD=kxuiceberg
      - POSTGRES_DB=kxuiceberg
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kxuiceberg" ]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"

  minio-s3:
    networks:
      iceberg-net:

  minio-s3-init:
    networks:
      iceberg-net:

  spark-iceberg:
    volumes:
      - ./spark/spark-defaults-minio-pg-catalog.conf:/opt/spark/conf/spark-defaults.conf #mount default config file   
    networks:
      iceberg-net:
    depends_on:
      pg-catalog:
        condition: service_healthy
      minio-s3-init:
        condition: service_completed_successfully

  spark-worker:
    volumes:
      - ./spark/spark-defaults-minio-pg-catalog.conf:/opt/spark/conf/spark-defaults.conf #mount default config file   
    networks:
      iceberg-net:

  spark-history-server:
    volumes:
      - ./spark/spark-defaults-minio-pg-catalog.conf:/opt/spark/conf/spark-defaults.conf #mount default config file   
    networks:
      iceberg-net:

  jupyter-notebook:
    volumes:
      - ./spark/spark-defaults-minio-pg-catalog.conf:/opt/spark/conf/spark-defaults.conf #mount default config file   
    networks:
      iceberg-net:

#volumes:
#  minio-s3-data:

networks:
  iceberg-net:
